# Generated by Django 5.2 on 2025-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_match_away_team_crest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='match_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
