# Generated by Django 5.2 on 2025-04-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='match_away_team_shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='match_home_team_shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
